# Generated by Django 4.1.3 on 2022-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('MobileNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('rentalamount', models.IntegerField()),
                ('tractormodel', models.CharField(max_length=30)),
            ],
        ),
    ]
