# Generated by Django 4.1.3 on 2022-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_hire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='hire',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='numofdays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='Address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='MobileNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rentalamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='tractormodel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
